### PR TITLE
Revise ref 2 typo & add figure titles in how-to-contribute.md

### PR DESCRIPTION
**Pull request by bowen0701**
Revise ref 2 typos in how-to-contribute.md.

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks. Can you resolve the error?

**Comment by astonzhang** [comment]
Thanks. Could you omit figure numbering in the caption? Latex will automatically generate figure indices. Although it doesn't show up in html, we are exploring a couple of alternatives now...

**Comment by astonzhang** [comment]
Thanks Bowen!

**Comment by bowen0701** [comment]
Thank you Aston!

**Comment by astonzhang** [comment]
Hi @bowen0701 thanks for your contributions to d2l-en (https://github.com/d2l-ai/d2l-en). Do you mind re-licensing all your contributions to us under the new license: MIT-0 for code and CC-BY-SA for text? This will allow more people to use d2l-en for free. All you need to do is replying to this message. Thanks.

**Comment by bowen0701** [comment]
Hi Aston,

Sure, it is my pleasure to contribute to this great book.

Thanks a lot!

Best wishes,
Bowen

**Comment by astonzhang** [comment]
Thanks Bowen!

**Pull request merged**
